### ISSUE TITLE
Jenkins prefix in Puppet

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_infra#1]
In der Puppet-Konfiguration fehlt das automatische Setzen eines Kontext-Pfades für Jenkins:

Änderung in der /etc/default/jenkins

```
JENKINS_ARGS="... --prefix=$PREFIX"
```

Hinweis: Kann evtl. in Puppet über file_inline erzeugt werden?

**Comment by ahus1** [comment]
Fixed in PR #14 - please doublecheck

**Comment by ascheman** [comment]
Well fixed in #14, thanks to @ahus1!

**Comment by ahus1** [comment]
PR still needs to be merged and applied to production.

**Comment by ahus1** [comment]
Content Security Policy settings don't seem to be applied to dev.dukecon.org - jgiven report doesn't work - https://dev.dukecon.org/jenkins/job/dukecon_server_develop/ws/impl/target/jgiven-reports/html/index.html

Therefore I suppose puppet hasn't been run yet?!

**Comment by ascheman** [comment]
Ran puppet, seems to work now ...
