### ISSUE TITLE
KeyCloak HTTPS

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_infra#13]
Migrate KeyCloak to https on production. Apache Setup is already working, cf. https://keycloak.dukecon.org/auth/. As soon as another link is opened, e.g., https://keycloak.dukecon.org/auth/realms/master/ it is redirected to unsecure http (http://keycloak.dukecon.org/auth/realms/master/). 

Check out http://keycloak.github.io/docs/userguide/keycloak-server/html/server-installation.html#d4e348 to perform this.

@srose or @ahus1 if you have done this already you are welcome to help with this enhancement.

**Comment by ahus1** [comment]
I suppose the section "3.2.7.2. Enable SSL on a Reverse Proxy" is the one you want to follow as you use Apache as a reverse proxy?

**Comment by srose** [comment]
standalone.xml looks good to me, apache setup as reverse proxy requires X-Forwarded-For and X-Forwarded-Prot to be set. 
Within keycloak a setting to enforce ssl (on external connections)

What about the certificates?

**Comment by ascheman** [comment]
Thanks, guys!

I have already created an extended Docker image with a standalone with additional configurations for https (cf. https://github.com/dukecon/keycloak_postgres_https). And I have added the Proto Header to Apache (I think the X-Forwarded-For header is automatically set by mod_proxy?). 

However I still cannot get https to work. Of course, I can access https://keycloak.dukecon.org/auth/ and other URLs. But as soon as I get a result back the protocol is rewritten to http again.

Any ideas welcome!

@srose certificates do not matter since the SSL session is terminated on the Apache and I already have a valid certificate in place.

**Comment by dasniko** [comment]
I just had the same issue...

AWS-Environment, Elastic-LoadBalancer, dedicated EC2 instance
SSL-termination on Elastic-LB, LB supports X-Forwarded Headers out-of-the-box (http://amzn.to/1mV6gbX)

LB Port 80 -> KC Port 8080
LB Port 443 -> KC Port 8080

`standalone.xml` config as described in above mentioned doc chapter.

Works. :-)

(Despite this doesn't/shouldn't matter: my realms don't enforce SSL at all, as the LB is only available through SSL from external. The EC2 instance itself is not accessible from external, only internal.)

So, if you have configured the standalone.xml correctly, I assume, you should inspect your X-Forwarded headers!?

**Comment by ahus1** [comment]
There was a mismatch in the apache configuration: `headers` needed to be replaced by `request_headers`, this way the forwarded headers are modified and not the response headers (?) sent to the client. 

Changes pushed to the branch already as part of 9cbaf2f097ce01b33a33fdfd1489af0e4909600d

I am unable to test it here as the docker image is still downloading. Maybe someone else will have a go on this. I've seen the header forwarded correctly by issuing a `nc -l 9091`

**Comment by ahus1** [comment]
Tested and verified locally. Works for me - no more redirects. I took the liberty to move one big XML configuration file to a JBoss CLI script - https://github.com/dukecon/keycloak_postgres_https/commit/ce8ec520e8fd4d25b2fe95eff9cca534a96bf0ed

@ascheman - Ready to be closed?

**Comment by ascheman** [comment]
Thanks, works now: https://keycloak.dukecon.org/auth/
