### ISSUE TITLE
Jenkins can't send email to feedback@dukecon.org on failed builds

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_infra#18]
See build: https://dev.dukecon.org/jenkins/job/dukecon_server_docker_develop/305/console

Sending e-mails to: feedback@dukecon.org
ERROR: Invalid Addresses
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
    com.sun.mail.smtp.SMTPAddressFailedException: 550 5.1.1 feedback@dukecon.org: Recipient address rejected: User unknown in local recipient table

**Comment by ascheman** [comment]
I hope I solved the problem!
