### ISSUE TITLE
Keycloak Emails are classified as Spam -> change settings of SMTP server!?

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_infra#19]
_From @dasniko on January 28, 2016 14:51_

All the KC verification emails are gone into my spam folder, so I didn't see them in beneath the 5 mins timeslot (perhaps extend this to 60 mins or so?).

I'm not an expert in configuring SMTP settings, but there are some things like "SPF" record/filter(?) and others, which leads to better results, when set correctly.

If users are not aware of this, they might not be able to use the application.

_Copied from original issue: dukecon/dukecon_html5#52_

**Comment by ascheman** [comment]
Added SPF record for dukecon.org: `v=spf1 mx ~all` (cf. https://en.wikipedia.org/wiki/Sender_Policy_Framework#Mechanisms). 

Please retest, as most of my mails are handled by the same smtp relay.

**Comment by dasniko** [comment]
did 2 tests:
- 1 mail was received in inbox, but marked by my mail app as "spam"
- 1 mail was received in spam-folder

**Comment by ascheman** [comment]
## Could you find out the spam classifications (usually some header lines)? Then we could check if it depends on SPF rules or something else.

Gerd Aschemann - mobil - +49 173 3264070

Am 9. Februar 2016 21:09:07 MEZ, schrieb "Niko Köbler" notifications@github.com:

**Comment by dasniko** [comment]
In the order of my previous comment (I removed the email addresses):

```
X-Envelope-From: <...>
X-Envelope-To: <...>
X-Delivery-Time: 1455048194
X-UID: 57963
Return-Path: <...>
Authentication-Results: strato.com 1;
    spf=pass
        smtp.mailfrom="...";
    dkim=none;
    domainkeys=none;
    dkim-adsp=none
        header.from="..."
X-Strato-MessageType: email
X-RZG-CLASS-ID: mi
Received-SPF: pass
    (strato.com: domain dukecon.org designates 148.251.114.20 as permitted sender)
    mechanism=mx;
    client-ip=148.251.114.20;
    helo="mail.our-isp.org";
    envelope-from="...";
    receiver=smtp.rzone.de;
    identity=mailfrom;
Received: from mail.our-isp.org ([148.251.114.20])
    by smtp.rzone.de (RZmta 37.17 OK)
    with ESMTPS id 4041b0s19K3EsR0
    (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (curve secp521r1 with 521 ECDH bits, eq. 15360 bits RSA))
    (Client did not present a certificate)
    for <...>;
    Tue, 9 Feb 2016 21:03:14 +0100 (CET)
Received: from dukecon0.dukecon.org (unknown [136.243.123.67])
    by mail.our-isp.org (Postfix) with ESMTPSA id 4844BE01A5
    for <...>; Tue,  9 Feb 2016 21:03:14 +0100 (CET)
Received: from 8805da9c0d37 (unknown [172.17.0.13])
    by dukecon0.dukecon.org (Postfix) with ESMTP id 08897A0419
    for <...>; Tue,  9 Feb 2016 21:03:17 +0100 (CET)
Date: Tue, 9 Feb 2016 20:03:17 +0000 (UTC)
From: ...
To: ...
Message-ID: <1570559124.23.1455048197017@8805da9c0d37>
Subject: Reset password
MIME-Version: 1.0
Content-Type: multipart/alternative; 
```

```
X-Envelope-From: <...>
X-Envelope-To: <...>
X-Delivery-Time: 1455048356
X-UID: 1297
Return-Path: <...>
Authentication-Results: strato.com 1;
    spf=pass
        smtp.mailfrom="...";
    dkim=none;
    domainkeys=none;
    dkim-adsp=none
        header.from="..."
X-Strato-MessageType: email
X-RZG-CLASS-ID: mi
Received-SPF: pass
    (strato.com: domain dukecon.org designates 148.251.114.20 as permitted sender)
    mechanism=mx;
    client-ip=148.251.114.20;
    helo="mail.our-isp.org";
    envelope-from="...";
    receiver=smtp.rzone.de;
    identity=mailfrom;
Received: from mail.our-isp.org ([148.251.114.20])
    by smtp.rzone.de (RZmta 37.17 OK)
    with ESMTPS id f06d46s19K5ul4M
    (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (curve secp521r1 with 521 ECDH bits, eq. 15360 bits RSA))
    (Client did not present a certificate)
    for <...>;
    Tue, 9 Feb 2016 21:05:56 +0100 (CET)
Received: from dukecon0.dukecon.org (unknown [136.243.123.67])
    by mail.our-isp.org (Postfix) with ESMTPSA id 7DECAE01A5
    for <...>; Tue,  9 Feb 2016 21:05:56 +0100 (CET)
Received: from 8805da9c0d37 (unknown [172.17.0.13])
    by dukecon0.dukecon.org (Postfix) with ESMTP id 421E0A0419
    for <...>; Tue,  9 Feb 2016 21:05:59 +0100 (CET)
Date: Tue, 9 Feb 2016 20:05:59 +0000 (UTC)
From: ...
To: ...
Message-ID: <1865768601.25.1455048359256@8805da9c0d37>
Subject: Link Github
MIME-Version: 1.0
Content-Type: multipart/alternative; 
```

**Comment by ascheman** [comment]
Looks like there was no explicit spam filter at work.  I was hoping for some extended headers:

Received: by mail.our-isp.org (Postfix, from userid 2000) id E557412667E; Mon,  8 Feb 2016 21:23:12 +0100 (CET)
Received: from dukecon0.dukecon.org (unknown [136.243.123.67]) by mail.our-isp.org (Postfix) with ESMTPSA id 72DEF126663 for gerd@dukecon.org; Mon,  8 Feb 2016 21:23:12 +0100 (CET)
Received: from 8805da9c0d37 (unknown [172.17.0.13]) by dukecon0.dukecon.org (Postfix) with ESMTP id 78688A0157 for gerd@dukecon.org; Mon,  8 Feb 2016 21:23:14 +0100 (CET)
X-Spam-Checker-Version: SpamAssassin 3.4.0 (2014-02-07) on mail.our-isp.org
X-Spam-Level:
X-Spam-Status: No, score=-2.9 required=5.0 tests=ALL_TRUSTED,BAYES_00, HTML_MESSAGE,URIBL_BLOCKED autolearn=ham autolearn_force=no version=3.4.0
Message-Id: 756504305.21.1454962994485@8805da9c0d37
Mime-Version: 1.0
Content-Type: multipart/alternative;  boundary="----=_Part_20_1594848634.1454962994484"
X-Bogosity: Ham, tests=bogofilter, spamicity=0.111436, version=1.2.4

Obviously SPF classification is OK now :-)

Have the mails been sorted out by your provider (Strato) already or by the client (I guess OSX?)?
If it's on the server side we could try to retrieve Strato's filter rules.
For the client side: Unfortunately I could not find out how the OSX junk mail filter works. Hence, we can hardly find out the root cause.

On 09.02.2016, at 22:31, Niko Köbler notifications@github.com wrote:

> In the order of my previous comment:
> 
> X-Envelope-From: <...>
> X-Envelope-To: <...>
> X-Delivery-Time: 1455048194
> X-UID: 57963
> Return-Path: <...>
> Authentication-Results: strato.com 1;
>     spf=pass
>         smtp.mailfrom="...";
>     dkim=none;
>     domainkeys=none;
>     dkim-adsp=none
>         header.from="..."
> X-Strato-MessageType: email
> X-RZG-CLASS-ID: mi
> Received-SPF: pass
>     (strato.com: domain dukecon.org designates 148.251.114.20 as permitted sender)
>     mechanism=mx;
>     client-ip=148.251.114.20;
>     helo="mail.our-isp.org";
>     envelope-from="...";
>     receiver=smtp.rzone.de;
>     identity=mailfrom;
> Received: from mail.our-isp.org ([148.251.114.20])
>     by smtp.rzone.de (RZmta 37.17 OK)
>     with ESMTPS id 4041b0s19K3EsR0
>     (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (curve secp521r1 with 521 ECDH bits, eq. 15360 bits RSA))
>     (Client did not present a certificate)
>     for <...>;
>     Tue, 9 Feb 2016 21:03:14 +0100 (CET)
> Received: from dukecon0.dukecon.org (unknown [136.243.123.67])
>     by mail.our-isp.org (Postfix) with ESMTPSA id 4844BE01A5
>     for <...>; Tue,  9 Feb 2016 21:03:14 +0100 (CET)
> Received: from 8805da9c0d37 (unknown [172.17.0.13])
>     by dukecon0.dukecon.org (Postfix) with ESMTP id 08897A0419
>     for <...>; Tue,  9 Feb 2016 21:03:17 +0100 (CET)
> Date: Tue, 9 Feb 2016 20:03:17 +0000 (UTC)
> From: ...
> To: ...
> Message-ID: 1570559124.23.1455048197017@8805da9c0d37
> Subject: Reset password
> MIME-Version: 1.0
> Content-Type: multipart/alternative;
> X-Envelope-From: <...>
> X-Envelope-To: <...>
> X-Delivery-Time: 1455048356
> X-UID: 1297
> Return-Path: <...>
> Authentication-Results: strato.com 1;
>     spf=pass
>         smtp.mailfrom="...";
>     dkim=none;
>     domainkeys=none;
>     dkim-adsp=none
>         header.from="..."
> X-Strato-MessageType: email
> X-RZG-CLASS-ID: mi
> Received-SPF: pass
>     (strato.com: domain dukecon.org designates 148.251.114.20 as permitted sender)
>     mechanism=mx;
>     client-ip=148.251.114.20;
>     helo="mail.our-isp.org";
>     envelope-from="...";
>     receiver=smtp.rzone.de;
>     identity=mailfrom;
> Received: from mail.our-isp.org ([148.251.114.20])
>     by smtp.rzone.de (RZmta 37.17 OK)
>     with ESMTPS id f06d46s19K5ul4M
>     (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (curve secp521r1 with 521 ECDH bits, eq. 15360 bits RSA))
>     (Client did not present a certificate)
>     for <...>;
>     Tue, 9 Feb 2016 21:05:56 +0100 (CET)
> Received: from dukecon0.dukecon.org (unknown [136.243.123.67])
>     by mail.our-isp.org (Postfix) with ESMTPSA id 7DECAE01A5
>     for <...>; Tue,  9 Feb 2016 21:05:56 +0100 (CET)
> Received: from 8805da9c0d37 (unknown [172.17.0.13])
>     by dukecon0.dukecon.org (Postfix) with ESMTP id 421E0A0419
>     for <...>; Tue,  9 Feb 2016 21:05:59 +0100 (CET)
> Date: Tue, 9 Feb 2016 20:05:59 +0000 (UTC)
> From: ...
> To: ...
> Message-ID: 1865768601.25.1455048359256@8805da9c0d37
> Subject: Link Github
> MIME-Version: 1.0
> Content-Type: multipart/alternative;
> —
> Reply to this email directly or view it on GitHub.

## 

Gerd Aschemann --- Veröffentlichen heißt Verändern (Carmen Thomas)
+49/173/3264070 -- gerd@aschemann.net -- http://www.aschemann.net

**Comment by dasniko** [comment]
The first one was classified by the provider. 

But I think you not only should make it work with Strato, but also with other major mail providers. Just to make sure it works.

**Comment by ascheman** [comment]
Sure, we should not find a solution for Strato only but something general.
I was only looking for a starting point for my investigation.
Cure by remote symptom analysis is a hard business.

To be honest, other providers seem not to have this problem?
We easily see the positive cases (of successful registrations) but can hardly find out which registrations we missed - and in particular if it was a problem of spam filtering or something else.

On 10.02.2016, at 07:31, Niko Köbler notifications@github.com wrote:

> The first one was classified by the provider.
> 
> But I think you not only should make it work with Strato, but also with other major mail providers. Just to make sure it works.
> —
> Reply to this email directly or view it on GitHub.

## 

Gerd Aschemann --- Veröffentlichen heißt Verändern (Carmen Thomas)
+49/173/3264070 -- gerd@aschemann.net -- http://www.aschemann.net
