### ISSUE TITLE
Set up Nagios monitoring for DukeCon / Javaland

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_infra#4]
TSSIA

**Comment by ascheman** [comment]
Basic Nagios monitoring of Host provider (Our-ISP) is in place (Apache, SSH, Disk). Extended monitoring (of misc. Services/URLs) will be postponed.

**Comment by ascheman** [comment]
Extended Nagios to monitor the following URLs
- https://dukecon.org/auth/ (KeyCloak)
- https://dukecon.org/jenkins/
- https://dukecon.org/nexus/
- https://dukecon.org/javaland/index.html
- https://dukecon.org/javaland/rest/conferences/

**Comment by ahus1** [comment]
You missed the following URL for a self check: 
https://dukecon.org/javaland/health

Actually there is currently a problem in production that we miss! I'll open a server bug in a second

**Comment by ascheman** [comment]
Added check for health also!
